# Generated by Django 4.2.30 on 2026-09-30 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aakarapp', '0033_taskzero_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('is_resolved', '-created_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-submitted_at',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('sort_order', '-id')},
        ),
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskzero',
            name='academic_year',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='taskzero',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskzero',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskzero',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskzero',
            name='crid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='one_submission_per_task_user'),
        ),
    ]
